import streamlit as st

def app():

    text =r'''
    # How does the Race Time Calculator work?

    ## Theory

    All classical motion is governed by Newton's laws, from the orbits of celestial bodies to the trajectory of a ball thrown in the air. 

    The movement of a race car is no different. For a CO2-cartridge powered foam car careening down a twenty-meter race track, Newton's second law dictates that the acceleration of the car can be predicted from the mass and forces acting on the vehicle. 

    More specifically, if $\mathbf{a}$ is the acceleration, $m$ is mass, and $\mathbf{F_{net}}$ is the sum of all the forces acting on our car, Newton's second law states:

    $$
    \mathbf{F_{net}}=m\mathbf{a}
    $$

    However, there are so many forces to consider. Thrust, rolling friction, drag, gravity, atmospheric pressure, torque, and lift all push or pull on the car. But, as we are only concerned with horizontal motion and some forces contribute more than others, we only need to care about the forces that matter.

    If we consider thrust and drag as the most significant horizontal forces, the equation that describes the motion of our car reduces to

    $$
    F_{net} = F_{thrust}-F_{drag}=ma
    $$

    Solving for acceleration,

    $$
    a = \frac{F_{thrust}-F_{drag}}{m}
    $$

    We see that the motion of our car is dependent on three variables: thrust, mass, and drag. If we know how all of these variables react to time, we will be able to completely describe the motion of our car given a variety of initial conditions.

    ## Thrust

    The thrust generated by the CO2 cartridge propells our car forward. Since all STEM Racing competitors are powered by the same cartridge, the thrust is invariant across all cars. 

    There are many ways to calculate the thrust over time. We can model the CO2 releasing from the cartridge as a insetropic process and analyticaly derive the thrust equation from thermodynamic principles. We can simulate the release of CO2 using a sufficiently fine mesh, an appropriate model, and a capable CFD solver. We can attach a cartridge on a heavy, low friction test car and track the movement of the car, making sure the effects of friction and drag are relatively insignificant.  

    Our engineering team opted for the last option since it required the least knowledge but the most validity. After tracking the position of the test car, the velocity was calculated and a logistic model was fitted to the velocity data. 

    ![image](https://github.com/user-attachments/assets/bb0bdd56-26d6-4427-86da-63a2487dff79)

    A corrective factor of $\frac{a}{1+e^{-c}}$ was subtracted from the sigmoid term to ensure that the intial velocity is zero.

    Other than fitting the data reasonably, the logistic model works well because the end behavior of the function matches what should happen in reality. Without drag, thrust should tend to zero as time passes and the velocity would asymptotically approach a maximum value, which the logistic model accounts for. 

    Multiplying the derivative of the velocity model by the mass of the test car should yield thrust. This yields the equation that the Race Time Calculator uses to find thrust:

    $$
    \text{Thrust} = F_{thrust}(t)=m_{test}\cdot\frac{a b e^{-(bt+c)}}{(e^{-(bt+c)}+1)^2}
    $$

    ## Mass

    Every gram increase in mass increases the race time by around 0.1 seconds. In this competition, this is a significant difference, so the 8g change in mass that occurs while our car rockets down the track must be accounted for. 

    The change in mass with respect to time $\dot{m}$ is equal to the product of density $\rho$, the area of the exit $A_e$, and exit velocity $v_e$. Since density is proportional to canister mass $m_c$ divided by canister volume $V$, we can form a differential equation for $m$:

    $$
    \frac{dm}{dt} = \frac{m_c}{V}A_ev_e
    $$

    $V$ and $A_e$ can be measured from an empty canister. However, the exit velocity of CO2 is much harder to measure. But we can always resort to theory.  

    Bernoulli's law states that the sum of pressure and kinetic energy in a fluid is a conserved quantity. 
    $$
    P_i+\frac{1}{2}\rho v_i^2=P_f+\frac{1}{2}\rho v_f^2
    $$

    If the initial velocity $v_1$ is zero (stagnation), the exit velocity $v_2$ can be solved for.

    $$
    v_f=\sqrt{\frac{2(P_i-P_f)}{\rho}}
    $$

    This equation has flaws. The intial pressure inside the canister is around $2.9\times10^7 \text{ Pa}$, and the density of CO2 in the canister is around $700 \frac{\text{kg}}{\text{m}^3}$. The initial exit velocity is then around $\sqrt{\frac{2\cdot 2.9\times10^7}{700}} \frac{\text{m}}{\text{s}}$ or $288 \frac{\text{m}}{\text{s}}$. This is greater than the speed of sound of CO2 at room temperature, which is around $267 \frac{\text{m}}{\text{s}}$. The exit velocity cannot be greater than the speed of sound, so we limit the velocity to be less than or equal to the speed of sound. 

    $$
    v_e=\min \left(c,\sqrt{\frac{2(P_c-101325 \text{ Pa})}{m_c/V}}\right)
    $$

    The canister pressure can be calculated using the Van Der Waals equation.

    $$
    P_c = \frac{RTm_c}{VM_m-bm_c}-\frac{am_c^2}{(VM_m)^2}
    $$
    Where 
    $$
    R = \text{Universal gas constant } \\
    T = \text{Temperature } \\
    V = \text{Canister volume } \\
    M_m = \text{Molar mass of CO}_2 \\
    a,b = \text{CO}_2\text{ gas constants}\\
    m_c = \text{Canister mass}
    $$

    ## Drag

    Drag is always present when the car moves. In fact, drag is the only relevant horizontal force that acts on the car after the CO2 in the canister has been exhausted. The drag force itself accounts for an increase of more than 0.2 seconds in race time.

    The drag force is dependent on the velocity of the car. This creates a level of complexity in the car's movement, as a higher drag creates higher deceleration, creating lower drag, reducing deceleration, and so on. Differential equations are therefore necessary to adequately describe our car's motion.

    The equation for drag force is:
    $$
    F_{drag} = \frac{1}{2}\rho_ac_dAv^2
    $$
    Where
    $$
    \rho_a = \text{Atmospheric density}\\
    c_d = \text{Drag coefficient of car}\\
    A = \text{Frontal area of car}\\
    v = \text{Velocity}
    $$
    $c_d$ can be found using CFD software, and most CAD modeling softwares have functions to determine $A$ by projecting the car onto a frontal plane.
    ## Putting it all together
    Now that we have found thrust, drag, and mass, we can finally describe acceleration. 
    Recall:
    $$
    a = \frac{F_{thrust}-F_{drag}}{m}\\
    $$
    Substituting for drag:
    $$
    a = \frac{1}{m}\left(F_{thrust}-\frac{1}{2}\rho_ac_dAv^2\right)
    $$
    Expressing the equation in terms of the position $x$ and rewriting the equation as a system of ODEs to get rid of second-order terms:
    $$
    \frac{dv}{dt} = \frac{1}{m}\left(F_{thrust}(t)-\frac{1}{2}\rho_ac_dAv^2\right)\\
    \frac{dx}{dt} = v
    $$
    Since we also know how mass evolves with respect to time, we define the vector $\mathbf{y}=[m,\dot{x},x]$ to express all three evolution equations in a compact manner.

    $$
    \mathbf{\dot{y}}
    =\begin{bmatrix} 
    \dot{m} \\ \dot{v} \\ \dot{x}
    \end{bmatrix}
    =\begin{bmatrix}
    \frac{m_c}{V}A_e\min \left(c,\sqrt{\frac{2(P_c(m_c)-101325 \text{ Pa})}{m_c/V}}\right) \\
    \frac{1}{m}\left(F_{thrust}(t)-\frac{1}{2}\rho_ac_dAv^2\right)\\
    v
    \end{bmatrix}

    \\
    \ \\
    m_c = m - m_0 + 0.008
    \\
    \ \\
    F_{thrust}(t)=m_{test}\cdot\frac{a b e^{-(bt+c)}}{(e^{-(bt+c)}+1)^2}
    $$




    '''
    st.markdown(text)